services:
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: projet7-rag-api:latest
    env_file:
      - .env
    environment:
      APP_ENV: docker
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      DATA_DIR: /app/data
      RAW_DATA_DIR: /app/data/raw
      PROCESSED_DATA_DIR: /app/data/processed
      VECTOR_STORE_DIR: /app/data/vector_store
      EVALUATION_DATA_DIR: /app/data/evaluation
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

  streamlit-ui:
    image: projet7-rag-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      API_BASE_URL: http://rag-api:8000
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    command: >
      streamlit run ui/streamlit_app.py
      --server.address 0.0.0.0
      --server.port 8501
      --browser.gatherUsageStats false
    ports:
      - "8501:8501"
    depends_on:
      - rag-api
